<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login_user_test_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c7b6df61-8c8f-4b02-b6da-e7ec65d3cb98</testSuiteGuid>
   <testCaseLink>
      <guid>736d7360-7531-44e1-a312-92d67943050a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/login_user/Validar el funcionamiento del login para un usuario cuando sus datos son correctos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>037e7f7f-03a6-4e8d-a92f-fb8d245dd1f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20daf891-6706-4c96-9d4c-552f4d675dbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6c4c0e6-75d5-4d02-bf0c-48fc55aceb42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0da342da-0ebf-48ef-b834-3d817c663204</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/login_user/Validar el funcionamiento del login para un usuario cuando sus datos son incorrectos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdca0984-8bbe-4c44-8f0b-1bfa4f0c4241</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65701ae7-b1fe-46fe-a8f7-f2ac8c0b1ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4939d7fc-3c6e-489b-9d19-9c7ee674e44e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d4e156-c8a3-4395-9d9c-a183e7075e44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ff495a4-b78e-4017-96f7-65cd889a5136</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/login_user/Validar el funcionamiento del logout para un usuario</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941f952c-61b0-49a7-af4b-91371ca16614</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6de8c113-5261-4179-97df-ff201e8327df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8766d496-a7e6-4671-8616-f22b971522af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acad6c66-7778-4bc4-aeed-c7469a72664d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/login_user/Validar el mensaje de error cuando no se ingresa un dato en el formulario de login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c0e3036-0cce-48b7-8821-9721db93ee71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fdc7649-be61-4b32-85b9-a40db128a324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eb24e6f-96af-4075-af98-fa6cb0aa0e02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c071600f-ab1f-415c-a174-2a27ee00ff6e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
