<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>register_user_test_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>178cf905-3123-4fc7-b44f-a031419c0a0a</testSuiteGuid>
   <testCaseLink>
      <guid>65472b60-fa68-4a75-86ea-7bdee5ce3103</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/register_user/Validar el funcionamiento correcto cuando se registra un usuario nuevo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce72b7e7-2ae2-469c-b6fa-9cbfb0b1f918</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e678131-907c-462b-955f-e5bcdad7a9dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90e88fe2-130f-497e-a924-d8ec1e049bd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bed9a6ce-4b2d-4d75-977e-4344bb6c8303</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b170e2a-dc88-44af-8a12-dade54abfe46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5d21aa-ff7b-4161-8f7e-c325752110cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c15939a1-26da-4ff5-aa79-d47cba080fe0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9e1ea04-399e-46b8-a164-5bab30cebfce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/register_user/Validar el mensaje de error cuando se intenta el registro de un usuario sin Politicas de Privacidad</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b72338b8-1a58-4638-a09a-5c32fa9361df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0f10b4-5a4d-46d0-918b-0b7ea030988a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16fbd3b5-b3ae-4732-b5a7-3b401f6dd7c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6606ec5f-db32-4242-b06d-7ca8ee603727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b6a7cca-25a6-4175-9b30-fb4501c9e683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20fe06b8-5a98-45bd-a1cc-a3e177018127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db9f0e13-7ac4-4a6b-8aed-f18b7e600746</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8258bf43-c68a-4b50-9655-6ee6f4c204e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/register_user/Validar el mensaje de error cuando se intenta el registro de un usuario sin un Parametro</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9f87c68-b092-40d0-a3c1-6af4afa5b406</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ad24edc-171d-4440-bde2-0a85df24f52a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49ce52b5-8280-4dbc-a372-c1924901d3bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d03fc05a-5fa7-4eec-b9ce-a251ba5a2adb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a676d60-8743-4da5-825c-bf0ae17b9f68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f7a42c1-89e9-46d1-88be-e98f75c6a959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87a91ab9-8ec0-4715-b191-e565632a2da7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccf145ea-16f1-4adf-ab17-74927957745c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/register_user/Validar el mensaje de error cuando se registra un usuario existente</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>381e15f7-36d5-44bf-992e-beee2199d2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95ba983b-0135-44ea-ae2f-285cff7024c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dee0b981-4fc4-4cbd-8f08-d2463e66a572</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2110e753-9f46-45c3-9d37-f33a166ead6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d3a77f-8fda-4cff-930d-b0d9cb61e312</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f46b6e63-94b4-48ac-a6c0-707dfda8aa56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2402ca12-8185-4564-beeb-6dabbf5d03c9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
