<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>shopping_cart_test_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a4cc6aec-736b-4beb-ac46-3dee353441ee</testSuiteGuid>
   <testCaseLink>
      <guid>6da7abdf-a049-4331-9b97-2b2c797bed9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/shopping cart/Validar carga de producto en el carrito de compras</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a81cc8ab-cfb0-4f2c-99f9-f6a4cfa0ae9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>922f2f1e-77dd-4e6b-afd4-af1f1c8c5b12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df9dc83b-9d9d-48eb-8aa7-b54e67d393b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02eb18cd-f28d-4c8c-9f0a-c84af65abe64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fda2d2b-2989-4034-947b-515bbe96b140</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/shopping cart/Validar la eliminacion de un producto en el carrito de compras</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>608db07d-db38-49a2-82be-cb68229642bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f9d3b78-ecbe-48f6-850f-bd5f4334eba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9063bba5-98b8-4fab-9763-efab77ee3892</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a61f5aad-f2bc-4d67-82af-16bba3cc9aff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62e0afed-2848-444d-a15e-bdb8f73001cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/shopping cart/Validar la eliminacion de un producto favorito</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3d11489-aadf-459e-838b-068815cdd134</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f49bba-0aa1-4c06-9f77-9e985a3364b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26465eae-8893-4595-9995-7535b8853454</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13553f64-4cc7-4015-97b1-e7d6754055ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0d6cec3-4df5-4e86-b9f7-5374ded6449a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/shopping cart/Validar la seleccion de producto favorito</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3308556f-76e9-4650-afe4-647af3832948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07f4345e-d87f-4eff-b2a6-52fdef36fe6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c03c4053-01ae-4e01-a96b-2fb9e0aa865c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a00418a0-dd45-4dbf-97b4-c023087b9980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>836094f3-872a-4cbb-a8f3-a9cdf900565c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/your_site/shopping cart/Visualización correcta del mensaje de comparar producto</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8f2ebc-8db8-433a-a24f-1381611762de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d62ad8-5316-4468-9c17-26ff872be4d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e77112f-cf09-4fbf-bf5a-7a2833ae2bf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce89f0c-d296-4978-90a6-2be6c4e68627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>333fdf6e-f482-47df-bf71-00f41a4fd2c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ef4d522-726c-4934-84d1-3606fbaa1b73</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
